/* Simulation code for SimpleThermalMVP generated by the OpenModelica Compiler v1.26.0-dev-355-ga153c00d2e-cmake. */
#if !defined(SimpleThermalMVP__MODEL_H)
#define SimpleThermalMVP__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"
#include "simulation/solver/synchronous.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "SimpleThermalMVP_functions.h"


extern void SimpleThermalMVP_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void SimpleThermalMVP_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int SimpleThermalMVP_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int SimpleThermalMVP_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int SimpleThermalMVP_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int SimpleThermalMVP_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int SimpleThermalMVP_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int SimpleThermalMVP_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int SimpleThermalMVP_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int SimpleThermalMVP_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int SimpleThermalMVP_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int SimpleThermalMVP_checkForAsserts(DATA *data, threadData_t *threadData);
extern int SimpleThermalMVP_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int SimpleThermalMVP_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int SimpleThermalMVP_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* SimpleThermalMVP_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* SimpleThermalMVP_relationDescription(int i);
extern void SimpleThermalMVP_function_initSample(DATA *data, threadData_t *threadData);
extern int SimpleThermalMVP_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int SimpleThermalMVP_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int SimpleThermalMVP_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int SimpleThermalMVP_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int SimpleThermalMVP_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int SimpleThermalMVP_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int SimpleThermalMVP_initialAnalyticJacobianH(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int SimpleThermalMVP_functionJacG_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int SimpleThermalMVP_functionJacA_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int SimpleThermalMVP_functionJacB_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int SimpleThermalMVP_functionJacC_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int SimpleThermalMVP_functionJacD_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int SimpleThermalMVP_functionJacF_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int SimpleThermalMVP_functionJacH_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern const char* SimpleThermalMVP_linear_model_frame(void);
extern const char* SimpleThermalMVP_linear_model_datarecovery_frame(void);
extern int SimpleThermalMVP_mayer(DATA* data, modelica_real** res, short *);
extern int SimpleThermalMVP_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int SimpleThermalMVP_getInputVarIndicesInOptimization(DATA* data, int* input_var_indices);
extern int SimpleThermalMVP_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int SimpleThermalMVP_setInputData(DATA *data, const modelica_boolean file);
extern int SimpleThermalMVP_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void SimpleThermalMVP_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void SimpleThermalMVP_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int SimpleThermalMVP_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void SimpleThermalMVP_read_simulation_info(SIMULATION_INFO* simulationData);
extern void SimpleThermalMVP_read_input_fmu(MODEL_DATA* modelData);
extern void SimpleThermalMVP_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int SimpleThermalMVP_inputNames(DATA* data, char ** names);
extern int SimpleThermalMVP_dataReconciliationInputNames(DATA* data, char ** names);
extern int SimpleThermalMVP_dataReconciliationUnmeasuredVariables(DATA* data, char ** names);
extern int SimpleThermalMVP_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int SimpleThermalMVP_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int SimpleThermalMVP_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "SimpleThermalMVP_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(SimpleThermalMVP__MODEL_H) */


