/* Additional record code for SimpleThermalMVP generated by the OpenModelica Compiler v1.26.0-dev-355-ga153c00d2e-cmake. */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "SimpleThermalMVP_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

